# Generated by Django 4.0.7 on 2022-12-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Features Name')),
                ('icon', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'transportation_features',
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'transportation_policies',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name of Transportation')),
                ('price_per_night', models.PositiveSmallIntegerField(help_text='Amount should be in THB.', verbose_name='Price per Night')),
                ('is_free_cancelation', models.BooleanField(default=False, verbose_name='Free Cancelation')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Maximum number of people affordable')),
                ('bag', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum number of bags affordable')),
                ('is_air_conditioned', models.BooleanField(default=True, verbose_name='Is air-conditioner installed')),
                ('number_of_doors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of doors')),
                ('gear_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('electirc', 'Electric')], default='auto', max_length=10, verbose_name='Gear Type')),
                ('car_type', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('luxury', 'Luxury'), ('people_carrier', 'People Carrier'), ('suv', 'SUV'), ('van', 'Van')], default='small', max_length=20, verbose_name='Car Type')),
                ('features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transportation', to='transportations.features', verbose_name='Features')),
                ('policies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transportation', to='transportations.policies', verbose_name='Policies')),
            ],
            options={
                'verbose_name': 'Transportation',
                'verbose_name_plural': 'Transportations',
                'db_table': 'transportations',
            },
        ),
    ]
