# Generated by Django 4.0.7 on 2022-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'blank': 'Email address cannot be empty.', 'null': 'You should provide an email address.'}, help_text='Email address must be unique and valid.', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(error_messages={'blank': 'Your first name cannot be empty.', 'null': 'You should provide your first name.'}, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(error_messages={'blank': 'Your first name cannot be empty.', 'null': 'You should provide your first name.'}, max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Phone Number')),
                ('is_host', models.BooleanField(default=False, verbose_name='Host')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active User')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
