# Generated by Django 4.2.3 on 2023-07-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="Is Host?"),
        ),
    ]
