# Generated by Django 4.0.7 on 2022-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'First name cannot be empty.', 'null': 'You should provide your first name.'}, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Last name cannot be empty.', 'null': 'You should provide your last name.'}, max_length=100, verbose_name='Last Name'),
        ),
    ]
