# Generated by Django 4.0.7 on 2022-11-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'blank': 'Nickname cannot be empty.', 'null': 'You should provide your nickname.'}, help_text='Can only include lower/uppercases numbers, . and _. This nickname will be shown on the profile of the host. If not specified, first name field would appear.', max_length=20, verbose_name='Nickname'),
        ),
    ]
