# Generated by Django 4.2.1 on 2023-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomamenity",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Icon"
            ),
        ),
        migrations.AddField(
            model_name="roomamenity",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
