# Generated by Django 4.2.1 on 2023-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_room_amenity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="amenity",
            field=models.ManyToManyField(
                related_name="rooms", to="rooms.roomamenity", verbose_name="Amenities"
            ),
        ),
    ]
