# Generated by Django 4.2.1 on 2023-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_room_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="amenity",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms",
                to="rooms.roomamenity",
                verbose_name="Amenities",
            ),
        ),
    ]
