# Generated by Django 4.2.1 on 2023-05-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_alter_room_amenity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("Apartments", "Apartments"),
                    ("Villas", "Villas"),
                    ("Beach Houses", "Beach Houses"),
                    ("Hotels", "Hotels"),
                    ("Resorts", "Resorts"),
                ],
                default="Apartments",
                max_length=100,
            ),
        ),
    ]
