# Generated by Django 4.2.1 on 2023-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_alter_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomamenity",
            name="name",
            field=models.CharField(max_length=124, verbose_name="Name"),
        ),
    ]
