# Generated by Django 4.2.1 on 2023-05-24 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0008_alter_roomamenity_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="type",
            new_name="room_type",
        ),
    ]
