# Generated by Django 4.2.1 on 2023-06-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0011_rename_amenity_room_amenities"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=124, unique=True, verbose_name="Room Type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
                "db_table": "room_types",
            },
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                default="Example RoomType",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rooms.roomtype",
                to_field="name",
                verbose_name="Room Type",
            ),
        ),
    ]
