# Generated by Django 4.2.2 on 2023-06-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0016_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image that will be used for image carousel in the home page.",
                null=True,
                upload_to="",
                verbose_name="Cover Image",
            ),
        ),
    ]
