# Generated by Django 4.2.2 on 2023-06-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0018_alter_room_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="rooms.roomtype",
                verbose_name="Room Type",
            ),
        ),
    ]
