# Generated by Django 4.2.2 on 2023-06-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0021_delete_roomtype_remove_roomamenity_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("apartment", "Apartment"),
                            ("condominium", "Condominium"),
                            ("villa", "Villa"),
                            ("resort", "Resort"),
                            ("castle", "Castle"),
                            ("beach House", "Beach House"),
                            ("luxe", "Luxe"),
                            ("cabin", "Cabin"),
                            ("cheateau", "Chateau"),
                            ("mansion", "Mansion"),
                            ("farm", "Farm"),
                        ],
                        default="hotel",
                        max_length=255,
                        verbose_name="Room Type",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.roomtype",
                verbose_name="Room Type",
            ),
        ),
    ]
