# Generated by Django 4.2.2 on 2023-06-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0023_alter_roomtype_options_alter_roomtype_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="rooms.roomtype",
                verbose_name="Room Type",
            ),
        ),
    ]
