# Generated by Django 4.2.2 on 2023-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0024_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("apartment", "Apartment"),
                    ("condominium", "Condominium"),
                    ("villa", "Villa"),
                    ("resort", "Resort"),
                    ("castle", "Castle"),
                    ("beach", "Beach House"),
                    ("luxe", "Luxe"),
                    ("cabin", "Cabin"),
                    ("cheateau", "Chateau"),
                    ("mansion", "Mansion"),
                    ("farm", "Farm"),
                ],
                default="hotel",
                max_length=255,
                verbose_name="Room Type",
            ),
        ),
    ]
