# Generated by Django 4.2.2 on 2023-07-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("rooms", "0026_alter_room_bathroom_alter_room_bedroom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="cities_light.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="cities_light.country",
                        verbose_name="Country",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rooms",
                to="rooms.roomaddress",
                verbose_name="Address",
            ),
        ),
    ]
