# Generated by Django 4.2.2 on 2023-07-06 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0027_roomaddress_room_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomaddress",
            options={
                "verbose_name": "Room Address",
                "verbose_name_plural": "Room Address",
            },
        ),
        migrations.AlterModelTable(
            name="roomaddress",
            table="room_addresses",
        ),
    ]
