databases:
  - name: letsh
    databaseName: letsh
    user: letsh
    region: singapore

services:
  - type: web
    name: letsh
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn letsh.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: letsh
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
