# Generated by Django 4.0.7 on 2022-10-25 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Accomodation Name')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Night')),
                ('maximum_guests', models.PositiveSmallIntegerField(default=1, verbose_name='Maximum Number of Guests')),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Bedrooms')),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(default=1, verbose_name='Numeber of Bathrooms')),
                ('is_free_breakfast', models.BooleanField(default=False, verbose_name='Free Breakfast')),
                ('is_free_internet', models.BooleanField(default=False, verbose_name='Free Internet')),
                ('is_free_parking', models.BooleanField(default=False, verbose_name='Free Parking')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
            },
        ),
    ]
