# Generated by Django 4.0.7 on 2022-10-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_free_booking_cancelation',
            field=models.BooleanField(default=True, verbose_name='Free Booking Cancelation'),
        ),
    ]
