# Generated by Django 4.0.7 on 2022-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_amenity_room_number_of_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of room option.', max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='accomodations.amenity'),
        ),
    ]
