# Generated by Django 4.0.7 on 2022-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0003_alter_room_amenities_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('house', 'House'), ('apartment', 'Apartment'), ('guesthouse', 'Guesthouse')], default='hotel', max_length=20, verbose_name='Room Category'),
        ),
        migrations.AlterModelTable(
            name='amenity',
            table='amenities',
        ),
    ]
