# Generated by Django 4.0.7 on 2022-10-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0003_amenity_description_room_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.AlterModelTable(
            name='amenity',
            table=None,
        ),
    ]
