# Generated by Django 4.0.7 on 2022-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0004_room_room_category_alter_amenity_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='amenity',
            name='desription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
