# Generated by Django 4.0.7 on 2022-11-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0005_remove_amenity_created_at_remove_amenity_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='desription',
            new_name='description',
        ),
    ]
