# Generated by Django 4.0.7 on 2022-11-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('accomodations', '0006_rename_desription_amenity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_category',
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
