# Generated by Django 4.0.7 on 2022-12-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0012_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.PositiveIntegerField(verbose_name='Price Per Night'),
        ),
    ]
