# Generated by Django 4.2.1 on 2023-05-21 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0004_alter_room_amenity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date & Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated Date & Time"
                    ),
                ),
                (
                    "adult",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Number of adults"
                    ),
                ),
                (
                    "children",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Number of children",
                    ),
                ),
                (
                    "check_in",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Check-in date"
                    ),
                ),
                ("check_out", models.DateField(verbose_name="Check-out date")),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reserved guest",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "db_table": "reservations",
            },
        ),
    ]
