# Generated by Django 4.2.1 on 2023-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_id",
            field=models.SlugField(
                default="20230531BAD578",
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
