# Generated by Django 4.2.1 on 2023-05-31 12:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0011_rename_amenity_room_amenities"),
        ("reservations", "0002_remove_reservation_id_reservation_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="adult",
            field=models.PositiveSmallIntegerField(
                default=2,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of adults",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reserved guest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_id",
            field=models.SlugField(
                default="20230531BBC987",
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
    ]
