# Generated by Django 4.2.1 on 2023-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0003_alter_reservation_adult_alter_reservation_guest_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_id",
            field=models.SlugField(
                default="20230618186710",
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
