# Generated by Django 4.2.2 on 2023-06-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_alter_reservation_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.SlugField(default='20230621E85ED5', editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
