# Generated by Django 4.2.2 on 2023-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0017_alter_reservation_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_id",
            field=models.SlugField(
                default="2023062185013D",
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
