# Generated by Django 4.2.2 on 2023-06-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0017_alter_roomtype_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomTypeThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date & Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated Date & Time"
                    ),
                ),
                ("file", models.ImageField(upload_to="", verbose_name="Photo file")),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.roomtype",
                        verbose_name="Photos for room_type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo for room type",
                "verbose_name_plural": "Photos for room type",
                "db_table": "photo_room_type",
            },
        ),
        migrations.CreateModel(
            name="RoomPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.URLField(verbose_name="Photo")),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="rooms.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo for room",
                "verbose_name_plural": "Photos for room",
                "db_table": "photo_room",
            },
        ),
    ]
