# Generated by Django 4.2.2 on 2023-06-28 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoomTypeThumbnail",
        ),
    ]
