# Generated by Django 4.2.2 on 2023-07-13 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_delete_roomtypethumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomphoto",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created Date & Time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomphoto",
            name="thumbnail",
            field=models.URLField(default=1, verbose_name="Thumbnail Image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomphoto",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated Date & Time"
            ),
        ),
        migrations.AlterField(
            model_name="roomphoto",
            name="photo",
            field=models.URLField(blank=True, null=True, verbose_name="Photo"),
        ),
    ]
