# Generated by Django 4.2.1 on 2023-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_remove_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Category name"),
        ),
    ]
