# Generated by Django 4.0.7 on 2022-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('room', 'Room'), ('house', 'House'), ('hotel', 'Hotel Apartments'), ('parking', 'Parking'), ('mobile', 'Mobile')], default='room', max_length=20, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
