# Generated by Django 4.2.2 on 2023-06-25 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="check_in",
            field=models.PositiveSmallIntegerField(
                help_text="How easy was it for checking in?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Check In",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="communication",
            field=models.PositiveSmallIntegerField(
                help_text="How well did room host communicate with customers?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Communication",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="location",
            field=models.PositiveSmallIntegerField(
                help_text="Was location good or fair enough to reach out?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.PositiveSmallIntegerField(
                help_text="Was it valuable enough compared to the price per night?",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Value",
            ),
        ),
    ]
