# Generated by Django 4.0.7 on 2022-10-28 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_accuracy_review_communication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='review',
            name='communication',
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
