# Generated by Django 4.0.7 on 2022-11-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0007_remove_room_room_category_room_category'),
        ('user_media', '0002_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accomodations.room'),
        ),
        migrations.AlterField(
            model_name='video',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='accomodations.room'),
        ),
    ]
