# Generated by Django 4.0.7 on 2022-11-17 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='parking_size',
        ),
        migrations.AddField(
            model_name='parking',
            name='maximum_capacity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Capacity'),
            preserve_default=False,
        ),
    ]
